### ISSUE TITLE
Container ni qayerda qollash kerak

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-countries#1]
![image](https://user-images.githubusercontent.com/79502241/145229296-a668753c-5f93-43f3-97ce-850c9513554e.png)
![image](https://user-images.githubusercontent.com/79502241/145229341-69008dd2-04ea-40be-9708-869bcc979a0f.png)
 container odatda section, header, footer kabi teglar ichida berilgani yaxshi. chunki bu teglar butun oynani qoiplab turishi kerak

**Comment by BekzodLolayev** [comment]
to'g'irlandi
